### ISSUE TITLE
 Explode button label for translation 

### ISSUE THREAD

**Issue by hktuto** [motss/app-datepicker#102]
Since that user can change language of the calendar, I think adding “cancel-label” and “confirm-label” for the button to let user translate would be great

**Comment by motss** [comment]
@hktuto Thanks for the issue. Someone thought about this before and it has been added in as an enhancement. You can sure now change the labels but only applies to `app-datepicker-dialog` if you're aware of that.

You can change the labels to any text you want via `confirmLabel` and `dismissLabel`, like so:

```html
<!-- Changing labels of the datepicker dialog to 'zh-CN' -->
<app-datepicker-dialog confirm-label="确定" dismiss-label="取消"></app-datepicker-dialog>
```

Hope this helps.

**Comment by hktuto** [comment]
@motss great !! Thanks
