### ISSUE TITLE
Add events on dialog button clicks.

### ISSUE THREAD

**Issue by vpanchev** [motss/app-datepicker#109]
### Description
The 'app-datepicker' dialog buttons should fire events when clicked.

### Expected outcome
The 'app-datepicker' dialog buttons fire events when clicked.

### Actual outcome
Functionality is not currently implemented.

### Live Demo
-none-

### Browsers Affected
-all-

**Comment by motss** [comment]
@vpanchev Any use case for this?

**Comment by motss** [comment]
Closing this in favor of `v4`. Highly recommend using `v4` even if you are using `polymer`.

Thank you for the support.
