### ISSUE TITLE
Current date not accepted at first selection

### ISSUE THREAD

**Issue by punkratz312** [motss/app-datepicker#113]
Right after submitting the picker direct after opening it (current date is selected) the picker does **NOT** fire a changed event. If a make a selection to any date the property gets changed as expected, but not if i dont make a selection and i just want to select the current date.
So it seems that the initial date will not lead to fire a event after submitting.

**Comment by punkratz312** [comment]
hello?

**Comment by motss** [comment]
@punkratz312 Not sure which picker you're referring to, any reduced code sample would be helpful.

**Comment by motss** [comment]
Closing this due to no response.
