### ISSUE TITLE
Neon Animation is deprecated; replace with css animations? 

### ISSUE THREAD

**Issue by Thkasis** [motss/app-datepicker#115]
Hi, I'm a fan of this element. Just wondering if there is any plan to replace neon animation as it is deprecated ? Cheers

**Comment by motss** [comment]
@Thkasis Thanks for raising this concern. A fix will be on its way to tackle this with Web Animations as a replacement probably instead of refactoring it to use CSS animations.

Feel free to submit a PR if you're interested to give this issue a try 😄!

**Comment by Thkasis** [comment]
No problem, shifting away from neon animation has been a pain for myself as I have used it in my web apps. I have often managed to use iron pages instead which helps to move towards lazy loading stuff even more as well. But when it comes to this I am not sure that would be wise and it would probably make things even more complex. I would submit a PR if I could find some time.. can't promise for now though, Cheers

**Comment by motss** [comment]
Closing this in favor of `v4`. Please consider `v4` even if you are using `polymer`. Thank you for the support.
