### ISSUE TITLE
Dynamically changing minDate

### ISSUE THREAD

**Issue by stat92** [motss/app-datepicker#118]
Hi! I have two datepickers. First of which is the start of some interval and second is the end of that interval.
And it would be great to dynamically change `minDate` of the second `datepicker` depending on the start date. I see [here](https://github.com/motss/app-datepicker/blob/master/app-datepicker.html#L1770) that it will be implemented. I am searching for some workaround to that. Thanks in advance.

**Comment by motss** [comment]
Good day, @stat92.

I think this can be achieved without even needing the element to handle the trick.

By just listening to the changed value of one datepicker then act on the `minDate` of another datepicker. Does that sounds like a solution to you?

**Comment by stat92** [comment]
@motss. It works. Thank you.
