### ISSUE TITLE
with iOS 9.3.5 incomplete display of the component

### ISSUE THREAD

**Issue by WTober** [motss/app-datepicker#120]
### Description

One user of my PWA with iOS 9.3.5 does not see the days in the component.
There are no problems with newer versions of Safari on mobile. Any help is welcome!

### Actual outcome

screenshot example #from a user with ios 9.3.5
[https://drive.google.com/file/d/1DO-YfCqMxHHtdiCnrdexXbqSHUbupe7S/view?usp=sharing](url)

### Browsers Affected

- [x] mobileSafari for iOS9.3.5

**Comment by motss** [comment]
@WTober Could you please uplod the screenshot to Github again?

**Comment by WTober** [comment]
Photo is not good quality. I hope you can see that the dates are missing
![issue_with_ios9_3_5](https://user-images.githubusercontent.com/8019613/38470994-4a3e4b78-3b6b-11e8-8d56-1c7c60a03054.jpg)

**Comment by motss** [comment]
@WTober It might be due to the absence of Intl. Did you load the Intl polyfill on the said old Safari? See here for more details https://github.com/motss/app-datepicker#intldatetimeformat.

**Comment by WTober** [comment]
@motss Thank you for your hint. Updated my PWA and informed the user with iOS9.3.5. If I get a feedback then I'll contact you again.

**Comment by motss** [comment]
@WTober You're welcome. Well, I think I can safely close this issue now. 👍
