### ISSUE TITLE
minDate doesn't effects a year

### ISSUE THREAD

**Issue by stat92** [motss/app-datepicker#122]
### Description
Say datepicker has as minDate 16.04.2018. But it doesn't disable a years. So you can simply check 16.04.2017 with years picker.

### Expected outcome
Can't select year earlier than min year.

### Actual outcome
Can select year earlier than min year.

### Live Demo
Check for demo in web components https://www.webcomponents.org/element/motss/app-datepicker/demo/demo/index.html

### Steps to reproduce
1. Put a `app-datepicker` element in the page.
2. Open the page in a web browser.
3. Set minDate.
4. Try to select year earlier than minDate.

**Comment by stat92** [comment]
Why does ```_isListOfYearsSelected``` is called? I am adding another listener to identify disabled or not, but it has not been called:
```
<div class$="each-list-of-years [[_isListOfYearsSelected(selected)]] [[_isDisabledYear(item, minDate, maxDate)]]"
```
```
_isDisabledYear: function (item, minDate, maxDate) {
        var year = item.year;
        var max = this.maxDate;
        var min = this.minDate;

        return (max && year > max.getFullYear()) || (min && year < min.getFullYear()) ? ' is-disabled-year' : '';
      }
```

**Comment by motss** [comment]
@stat92 If not mistaken, `iron-list` calls it. `selected` is one property from `iron-list`. `iron-list` sets it to `true` when a list item is selected. `_isListOfYearSelected` will compute the class accordingly to the value of `selected`.

**Comment by motss** [comment]
@stat92 Perhaps re-render the year list when a `minDate` or `maxDate` is set?

**Comment by stat92** [comment]
@motss What's about [PR](https://github.com/motss/app-datepicker/pull/123) ?

**Comment by motss** [comment]
Closing this in favor of `v4`. Highly recommend using `v4` even if you are using `polymer`.

Thank you for the support.
