### ISSUE TITLE
Why is node 10.x.x required for this?

### ISSUE THREAD

**Issue by btopro** [motss/app-datepicker#143]
when installing "app-datepicker": "^3.0.0", in my own package it no longer allows it to work unless I update to node 10.

Is there a reason why you've required node 10+ via package.json here?

**Comment by motss** [comment]
@btopro 

Hi. Thanks for asking this.

We're using `node@10` when migrating to Polymer 3. If not mistaken, `node@10` is the latest LTS at that time. So we're recommending `node@10`.

I think `node@8` should work since the tests passed for `node@8`, `node@10`, and `node@11`.

**Comment by motss** [comment]
> in my own package it no longer allows it to work unless I update to node 10.

If that's the case, I can take a look at that to see if `node@8` works without any issues. If no, it can be changed to `node@8`.

May I know which version of `node@8` you are using now?

**Comment by btopro** [comment]
i was using 8, updated to 10 as part of this; just wasn't really sure why this was in there in the first place. Seems like something that should be left to the test engine but I just haven't included that ever anywhere before.

**Comment by motss** [comment]
It's mainly for development purpose. Since we need Node.js to build the script and run tests, the `engines` field in `package.json` is set to be consistent for contributors. It has nothing to do with the element itself since the element runs on browser environment.

**Comment by motss** [comment]
It's fixed in latest version `v3.1.0`.
