### ISSUE TITLE
Not working as per documentation:

### ISSUE THREAD

**Issue by LRagji** [motss/app-datepicker#149]
### Description
I am using https://unpkg.com/app-datepicker@3.1.0/app-datepicker.js when i render the element and select it using chrome inspect it is missing lot of properties mentioned in the documentation Eg:landscape, value etc what am i missing?

**Comment by motss** [comment]
@LRagji Are you using the doc from https://github.com/motss/app-datepicker/blob/master/api-references.md#appdatepicker? If yes, that is documentation for `v4.0.0-rc.19`.

For `v3.x`, please refer to https://motss.github.io/app-datepicker/components/app-datepicker/.

**Comment by motss** [comment]
Closing this issue as it is assumed to be resolved.
