### ISSUE TITLE
IE 11 - Date Picker does not show up on the page

### ISSUE THREAD

**Issue by kaseyhinton** [motss/app-datepicker#154]
### Description
The `app-datepicker` element wont work in IE 11. It throws a type error 

 TypeError: Unable to get property 'toString' of undefined or null reference at AppDatepicker (http://localhost:3000/node_modules/app-datepicker/dist/app-datepicker.js:230:7)

### Expected outcome
Date picker should show up and work in IE 11

### Actual outcome
Date picker not showing in IE 11 due to type error

### Live Demo
I do not have time to set up a live demo. Maybe later this week I can

### Steps to reproduce
My environment is Typescript 3.5.1 and Lit Element 2.2.0
1. Put a `app-datepicker` element in the page.
2. Open the page in a IE 11.
3. Open console to view error

### Browsers Affected
- [ ] Chrome/ Opera
- [ ] Firefox
- [ ] Safari 10+
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge 12+
- [X ] IE 11

**Comment by motss** [comment]
Which version of the datepicker are you using?

I actually have a demo at https://github.com/motss/app-datepicker/blob/master/README.md#demo. Does it work for you?

In the meantime, I'll take a look when I have my laptop with me.

**Comment by motss** [comment]
@kaseyhinton Do you have got tht time to work on a reduced test case? I've checked it on my side and it works on IE11 without any issue except for the animation glitch which was caused by Web Animations  polyfill. I might plan to remove animations completely on older browsers.

**Comment by kaseyhinton** [comment]
@motss The demo you have provided works for me in IE 11. I will try to set up a demonstration of the bug I am seeing. As far as the version is concerned I installed the latest available at the time. RC 24 I believe.

**Comment by kaseyhinton** [comment]
@motss Here is a repo I made that can reproduce the problem I am seeing. [demo](https://github.com/kaseyhinton/app-datepicker-demo) 

I tried to set up an example online but am having difficulty because codesandbox and codepen aren't working in IE-11 unfortunately.

**Comment by motss** [comment]
Errors are due to missing polyfills on IE11. It was mentioned inside the demo but not the docs.

https://github.com/motss/app-datepicker/blob/master/index.html#L19-L43

The line above is what you need to run the datepicker.

**Comment by motss** [comment]
> I tried to set up an example online but am having difficulty because codesandbox and codepen aren't working in IE-11 unfortunately.

For some reasons, the website does not work well on IE11. You still be able to view the actual site though. The trick is to wake the server up in supported browsers such as Chrome and visit the link again with IE11.

I've ensured that the demo site works on all browsers including IE11.

**Comment by kaseyhinton** [comment]
Ahh okay. Yeah it's working with the polyfills now. Thanks for getting back to me so promptly. This date picker will work really well for me! :)

**Comment by motss** [comment]
Glad to hear that it finally works for you. Feel free to open any issues you encounter. Thank you for supporting! 😄
