### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'addEventListener' of null at new Tracker (tracker.ts:91) at HTMLElement.updated (app-datepicker.ts:671)

### ISSUE THREAD

**Issue by CartmanErik** [motss/app-datepicker#157]
### Description
Have a problem with app-datepicker. Calendar doesn't show up. Instead of it I have some class in calendar window as text. Part of this class:
...
{ if (!(part instanceof NodePart)) { throw new Error('cache can only be used in text bindings'); } let templateCache = templateCaches.get(part); if (templateCache ...

In console I have errors:
Uncaught (in promise) TypeError: Cannot read property 'addEventListener' of null
    at new Tracker (tracker.ts:91)
    at HTMLElement.updated (app-datepicker.ts:671)
    at HTMLElement.performUpdate (updating-element.ts:215)
    at HTMLElement._enqueueUpdate (updating-element.ts:717)

### Expected outcome
Calendar should show up

### Actual outcome
Calendar doesn't show up. Instead of it I have some class in calendar window as text. Part of this class:
...
{ if (!(part instanceof NodePart)) { throw new Error('cache can only be used in text bindings'); } let templateCache = templateCaches.get(part); if (templateCache ...

In console I have errors:
Uncaught (in promise) TypeError: Cannot read property 'addEventListener' of null
    at new Tracker (tracker.ts:91)
    at HTMLElement.updated (app-datepicker.ts:671)
    at HTMLElement.performUpdate (updating-element.ts:215)
    at HTMLElement._enqueueUpdate (updating-element.ts:717)

### Browsers Affected

- [x ] Chrome/ Opera
didn't checked other browsers
![app-datepicker](https://user-images.githubusercontent.com/33684350/63212119-1780f980-c100-11e9-8daa-fc380b9c9e93.PNG)

**Comment by motss** [comment]
Do you have a reduced test case for this problem? What's the version of `lit-element` you are using?

**Comment by CartmanErik** [comment]
"lit-element": "^2.2.0",
    "lit-html": "^1.1.0"
To be honest I don't know how to reproduce test case. It works for some people but doesn't work for other. I tried to use previous version of datepicker and it works as it should. But v4 doesn't work for me.

**Comment by motss** [comment]
Thank you for the response. I'll keep this opened for a while and see if that happens again before closing this.

**Comment by kaseyhinton** [comment]
I was getting this problem too for a minute. I was using the newest chrome, lit, and app-datepicker. Once I restarted my node server this error went away and the datepicker started functioning as normal

**Comment by motss** [comment]
This should have been resolved by this e3cc4494917cfc2f0e30d0ee5792b0b2832638ed commit. Please give it a try and see if that resolves on your side.

**Comment by motss** [comment]
Closing this
