### ISSUE TITLE
Event on select date updated

### ISSUE THREAD

**Issue by gdevacc12** [motss/app-datepicker#165]
### Description
It would be very useful to be able to handle an event on: change of the selected date.
Forgive my ignorance but is not clear if this event is defined or how to handle it.
Perhaps it's just documentation or perhaps the dispatch for custom event could be added.
I could see some reference to DatepickerValueUpdatedEvent in app-datepicker.d.ts  but no corresponding dispatched event in app-datepicker.js

### Expected outcome
On clicking a valid date, a custom event is dispatched with the value of the selected date, e.g. "2020-01-31"

### Actual outcome
It's not clear if an event is generated or if it is, how to handle it.

### Prototype solution
To illustrate a solution, I added to app-datepicker.js at the end of _updateFocusedDate(ev)
```
dispatchCustomEvent(this, 'datepicker-value-updated', { value: this._focusedDate.toISOString().substr(0,10) });
```

Then could listen to the event from the host element (app-datepicker with id="datePicker):
```
 firstUpdated(changedProperties){
    const datePickerElement = this.shadowRoot.querySelector('#datePicker');
    datePickerElement.addEventListener('datepicker-value-updated', (e) => {console.log(e.detail.value)});
  }
```
I appreciate this is hack and may not be consistent with the TypeScript but it illustrates the desired behaviour.

**Comment by motss** [comment]
This sounds like a useful use case. This can be considered as a new feature.

**Comment by motss** [comment]
In cace473, a new event `datepicker-value-updated` has been added. It will take care of mouse clicks and keypress with some payload to identify what kind of source triggers the event. The doc will be updated soon before a new release is out.

Thanks for the issue. 👍

**Comment by motss** [comment]
📦  [v4.0.0-rc.41](c12446832110e17a71e30462e579535c5dae69cb) released! 🎉
