### ISSUE TITLE
blue rectangle on focus

### ISSUE THREAD

**Issue by cintaccs** [motss/app-datepicker#168]
### Description

The date picker shows a blue rectangle on focus.
Is it possible to get rid of that?

**Comment by motss** [comment]
For accessibility reason, you should not do that. I don't recommend you to do that but you can set `outline: none` for all focusable elements. You can however override `static get styles() { ... }` by extending `AppDatepicker`, see [simple demo].

Hope this helps. 😄 

[simple demo]: https://jsbin.com/kexigeyogi/edit?html,output

**Comment by cintaccs** [comment]
Thanks a lot for quick response! as well as the demo! I will try with that. In general I don't think the MDC components implements outline - in any case - it will always be a taste question - and in all cases it should be something the end users will decide / change / color theme etc.

**Comment by cintaccs** [comment]
Works great! Thanks a lot!
