### ISSUE TITLE
day numbers not exactly centered in day circle

### ISSUE THREAD

**Issue by cintaccs** [motss/app-datepicker#169]
### Description

The day numbers are not 100% centered - they are a little to the left in most cases. Any method to make them 100% centered in the picker circle?

**Comment by motss** [comment]
@cintaccs Do you mind sharing a screenshot or some sort?

**Comment by cintaccs** [comment]
<img width="239" alt="Screenshot 2020-02-16 at 16 28 02" src="https://user-images.githubusercontent.com/4300051/74607453-5442a300-50d9-11ea-8db2-9c624a3b6887.png">
<img width="310" alt="Screenshot 2020-02-16 at 16 27 49" src="https://user-images.githubusercontent.com/4300051/74607457-56a4fd00-50d9-11ea-8252-8c6f639d6da1.png">


I am using it embedded in 
```
<div class="mdc-dialog" role="${role}" aria-modal="true" aria-labelledby="${labelledby}">
            <div class="mdc-dialog__container">
                <div class="mdc-dialog__surface">                   
                    <div class="mdc-dialog__content" id="my-dialog-content"  style="${styleMap(styles)}">
<app-datepicker min="1970-01-01"></app-datepicker>
                    </div>
                    <footer class="mdc-dialog__actions"> ....
```

currently I am writing the mdc-dialog into the lit DOM - i.e. I am not using shadowDOM - however I believe your component should render irrespectively of what I do - right?

**Comment by motss** [comment]
Is that latest Chrome?

**Comment by cintaccs** [comment]
Version 80.0.3987.106 (Official Build) (64-bit)
