### ISSUE TITLE
highlight when hovering the year to indicate that it can be selected

### ISSUE THREAD

**Issue by cintaccs** [motss/app-datepicker#170]
### Description

similar to the hover on days

**Comment by motss** [comment]
This sounds like an enhancement. Good to know that.

**Comment by motss** [comment]
Looks like it was actually a bug. I've already supported that but with an invalid CSS custom property name and it has been renamed to use `--app-datepicker-focused-year-bg-color` for customization.

**Comment by cintaccs** [comment]
I am trying this 
   .calendars-container {
            --app-datepicker-focused-year-bg-color:  #f44336;
          --app-datepicker-accent-color: #f44336;
        }

the           --app-datepicker-accent-color: #f44336; have effect (on the days)
the --app-datepicker-focused-year-bg-color:  #f44336; have no effect on the year selector

**Comment by cintaccs** [comment]
just to make sure we talk about the same hover ... I am talking about the year on top of the date picker - hovering the year lines in the scroll list works. Although I didn't try setting the hovering color.
