### ISSUE TITLE
when dragging pages - hide the < > buttons during the drag operation

### ISSUE THREAD

**Issue by cintaccs** [motss/app-datepicker#171]
### Description

when dragging swiping month to month - the buttons have no effect and they actually looks bad on top of the moving month name + year. At least give it a try and see whether you agree.

**Comment by motss** [comment]
I decided not to have any effect on the buttons after seeing that it does not affect much on basically anything and we can still live without that. This might complicate the code a little bit. Plus, no clear specification on that as well even though we could see that on Android date picker.

Hope you understand that.

**Comment by cintaccs** [comment]
Understood ... I guess I can implement own opacity or visibility on drag operation events... would just be a simple thing for you to add a "is-dragging" class on the top container allowing for free sub-element styling. IMO you should try not to make too many of these static "taste" decisions as it will be "opinionated" (I think Google uses that expression a lot).

**Comment by cintaccs** [comment]
Actually it is hard to get to that drag operation through css settings alone... so if you one day feel excited about adding a top class to the container during drag operation (and remove it again at drag end) - then that would be great....
