### ISSUE TITLE
when using some locales (like Danish) . are entered after the days in the calendar view

### ISSUE THREAD

**Issue by cintaccs** [motss/app-datepicker#172]
<img width="1121" alt="Screenshot 2020-02-16 at 16 43 19" src="https://user-images.githubusercontent.com/4300051/74607746-979e1100-50db-11ea-9b13-181d616919f5.png">

at least in Denmark where I am from - we do not show . after each day in the calendar.
Maybe that also relates to the small issue with centering #169

**Comment by motss** [comment]
Cool. I'll take a look on this.
