### ISSUE TITLE
The field `sideEffects` in package.json is wrongly set to `false`

### ISSUE THREAD

**Issue by brainlessbadger** [motss/app-datepicker#181]
### Description
The field `sideEffects` in package.json file is set to false, while main file is only imported for sideEffects (it defines a customElement).

### Expected outcome
The field `sideEffects` should be `true`, since the file is imported for it's side effects (and in fact, doesn't seem to export anything).

### Actual outcome
The field `sideEffects` is set to `false`

### Browsers Affected
This is build-time issue rather then browser issue.

**Comment by motss** [comment]
That was an experiment back then and it should not be there actually. I've removed that flag in c4b69fef82f36934c40fd6f3073c7ba1727c1854.

This should resolve a lot of bundling issues.
