### ISSUE TITLE
app-datepicker not included by rollup

### ISSUE THREAD

**Issue by nicolasr75** [motss/app-datepicker#184]
I want to use app-datepicker in a lit-element based app and I am using rollup to build my app.

The problem is that rollup does not include app-datepicker in the build even though I have `import 'app-datepicker'` and am using the tag in one of my templates.

When I edit app-datepicker.js to include 

`export { customElementsDefine, Datepicker };`

and then in  my code do 

`import { customElementsDefine, Datepicker } from "app-datepicker";`

and 

`customElementsDefine('app-datepicker', Datepicker);`

rollup picks it up.

This might be related to https://github.com/motss/app-datepicker/issues/181

### Browsers Affected
Applies to all because the problem is already in the build step.

**Comment by motss** [comment]
@nicolasr75 Thanks for reporting it.

It has been identified that it was indeed caused by an issue mentioned in #181. I've fixed it already and published a new version.
