### ISSUE TITLE
nodemod dependency files not found

### ISSUE THREAD

**Issue by colscott** [motss/app-datepicker#200]
### Description
When building app-datepicker, getting an error along the lines of:
Module not found: Error: Can't resolve 'nodemod/dist/calendar/get-formatter.js' in '...\node_modules\app-datepicker\dist\helpers'

app-datepicker has nodemod ^2.7.2 dependency. When installing, nodemod 2.8.1 is pulled in. It looks like nodemod moved some files around between 2.7.2 and 2.8.1.

Looks like either the file imports needs to be fixed
```js
import { getFormatter } from 'nodemod/dist/calendar/get-formatter.js';
```
Or depend on exact version of nodemod 2.7.2.

### Steps to reproduce
Install app-datepicker 4.5.1 and install all dependencies.

Thanks :-)

**Comment by motss** [comment]
Thanks for the report.

Resolved in ff53ca490260efde28b8cc97412a7a9effda2881.
