### ISSUE TITLE
Installation problems in windows development environment

### ISSUE THREAD

**Issue by mrconsufed** [motss/app-datepicker#213]
### Description
We'd like to be able to use your component, but encounter problems during install on our windows x64 development machines.

### Expected outcome
yarn install for "app-datepicker": "^6.0.0-rc.30" and its dependencies completes successfully on windows x64 development machines.

### Actual outcome
install fails due to the unix-flavoured definition of the "postinstall" script in app-datepicker's package.json:

"postinstall": "FILE=\"$(npm root)/@reallyland/tools/postinstall.sh\"; if [ -f \"$FILE\" ]; then sh \"$FILE\"; fi"

### Live Demo
n/a

### Steps to reproduce
on a windows machine with Git installed (and C:\Program Files\Git\bin on the windows PATH to provide access to sh.exe), open a bash shell on a project that includes "app-datepicker": "^6.0.0-rc.30" in its dependencies and attempt a yarn install (we're using yarn 1.22.17 and node v18.12.1)

### Browsers Affected
n/a

**Comment by motss** [comment]
@mrconsufed Thanks for reporting this. I'm working on a fix to this.
