### ISSUE TITLE
SyntaxError in Safari 15.6

### ISSUE THREAD

**Issue by joe-bethke** [motss/app-datepicker#225]
### Description

The web component fails to render, causes syntax error in Safari 15.6 when running the demo app in this repo, and in a minimal application using `app-datepicker`.

```
SyntaxError: Unexpected token '{'
```

After doing some testing in my own application using `app-datepicker`, I found that this error seems to be triggered by [static_initialization_blocks](https://caniuse.com/mdn-javascript_classes_static_initialization_blocks), which are not supported in Safari 15.6. I found that, in my application, the stack trace for this syntax error pointed at the following code in my script, which correlates with this components source in [month-calendar.ts](https://github.com/motss/app-datepicker/blob/main/src/month-calendar/month-calendar.ts#L19)

```
class MonthCalendar extends RootElement {
      #selectedDate;
      #shouldFocusSelectedDate;
      static { this.shadowRootOptions = {
          ...RootElement.shadowRootOptions,
          delegatesFocus: true,
      }; }
```

This syntax is used a few times throughout `app-datepicker`'s source code. I see that Safari 15.4 is called out as a supported browser in the repo's [readme](https://github.com/motss/app-datepicker/tree/main?tab=readme-ov-file#browser-compatibility), but I think this is probably mistaken. For what it's worth, I also found a few instances where I had used this same syntax in my own lit components, and I found that I was able to mostly convert from the `static styles = { ... }` syntax to using the getter syntax instead: `static get styles() { ... }`. This solved this syntax error that was being triggered by my own code, however I found the same error popped up after fixing those problems in my component that was rendering `app-datepicker`.

### Expected outcome

The readme says that Safari 15.4 is supported, so my expectation is that the component renders in 15.6 as well.

### Actual outcome

```
SyntaxError: Unexpected token '{'
```

### Steps to reproduce

1. clone this repo
2. `npm i`
3. `npm run build`
4. `npm run serve`
5. navigate to `localhost:3030` in Safari 15.6
6. page is blank, observe console error `SyntaxError: Unexpected token '{'`

### Browsers Affected

- [ ] Chrome/ Opera
- [ ] Firefox
- [x] Safari 10+
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge 12+
- [ ] IE 11

**Comment by motss** [comment]
@joe-bethke Thanks for raising this issue. We need to fix that.
