### ISSUE TITLE
Date should not register known neon animation names

### ISSUE THREAD

**Issue by olegomon** [motss/app-datepicker#28]
In the latest release 2.7.0 there are some animation elements registered in [https://github.com/motss/app-datepicker/blob/master/app-datepicker-animations.html](https://github.com/motss/app-datepicker/blob/master/app-datepicker-animations.html)

- fade-in-animation
- fade-out-animation
- slide-from-left-animation
- slide-from-right-animation

If one of the elements inside the main application has a dependency to [https://github.com/PolymerElements/neon-animation/blob/master/neon-animations.html](https://github.com/PolymerElements/neon-animation/blob/master/neon-animations.html)
then those animations are being registered twice which causes:

`Uncaught NotSupportedError: Failed to execute 'registerElement' on 'Document': Registration failed for type 'fade-in-animation'. A type with that name is already registered.`

Is there any reason why you try to redefine those neon-animations?

Thanks, Oleg

**Comment by motss** [comment]
@olegomon No specific reason. Will get it fixed ASAP.
