### ISSUE TITLE
Help with CSS

### ISSUE THREAD

**Issue by nocquidant** [motss/app-datepicker#33]
Could you please tell me what is the CSS property to set to have a nice looking selected day (see image). 

Thanks 
-- nick

![image](https://cloud.githubusercontent.com/assets/217054/16583050/2ef1af0c-42b3-11e6-9a9a-745cf253d66b.png)

**Comment by motss** [comment]
```
app-datepicker {
    --app-datepicker-selected-date: {
    color: yellow;
  };
}
```

**Comment by nocquidant** [comment]
Actually I don't not need a yellow color :) The computed height is not right : the 2 lines overlaps ("dim. 5" and "juin").

**Comment by motss** [comment]
@nocquidant What browser you're on seeing this problem?

**Comment by nocquidant** [comment]
On Chrome and FF. Your demo looks good so it is probably one of my style rules...

**Comment by motss** [comment]
@nocquidant I thought so. I don't see any issue only current styling. You can try `line-height` for a little adjustment.

``` 
app-datepicker {
  --app-datepicker-selected-date: {
    line-height: 32px;
  };
}
```

**Comment by nocquidant** [comment]
OK it is much better. Thanks

Le mar. 5 juil. 2016 à 13:46, Rong Sen Ng <notifications@github.com> a
écrit :
