### ISSUE TITLE
Character cause error when compiling projects

### ISSUE THREAD

**Issue by darwinserrano** [motss/app-datepicker#34]
Hi.

I've been using this extension and compile the project to get errors. I could see that the problem is in the "demo/index.html" file, because there is a zero in the air within a style class, on line 170.

`
.locale_example {
        text-align: left;
        padding: 8px; 0
      }
`

Can you fix this? Please.

Regards

**Comment by motss** [comment]
@darwinserrano Mind submitting a PR for fix that?
