### ISSUE TITLE
datepicker `date` not working

### ISSUE THREAD

**Issue by gusdecool** [motss/app-datepicker#36]
Tested with this code:

`<app-datepicker-dialog id="endDatePicker" date="2017/05/17" with-backdrop entry-animation="datepicker-slide-from-bottom-animation" exit-animation="datepicker-slide-from-top-animation"></app-datepicker-dialog>`

notice that date is set `2017/05/17` but when the dialog opened it still show today date. e.g: 2016/08/03

How come?

**Comment by motss** [comment]
@gusdecool `input-date` is the right property for you to set a date while `date` is the output date when you select a date from the datepicker.

```html
<app-datepicker input-date="2017/05/17" date="{{selectedDate}}"></app-datepicker>
```

**Comment by gusdecool** [comment]
Thanks @motss will try it again tomorrow and back to you 👍

**Comment by motss** [comment]
@gusdecool just let me know if that solved that problem.

**Comment by gusdecool** [comment]
@motss the solution didn't work. 

scenario: i want to use datepicker with date that i have from polymer properties as the input date and this property will changed based on your datepicker

here is the code:

```html
<paper-button on-tap="openStartDate">{{ plan.startDate }}</paper-button>

<app-datepicker-dialog id="startDatePicker"
                                                   date="{{ plan.startDate }}"
                                                   input-date="{{ plan.startDate }}"
                                                   with-backdrop
                                                   entry-animation="datepicker-slide-from-bottom-animation"
                                                   exit-animation="datepicker-slide-from-top-animation"></app-datepicker-dialog>
```

```json
planDate: {
                    type: Object,
                    value: {
                        startDate: '2016/12/01',
                        endDate: '2016/12/31'
                    }
                }
};
```

- After the page loaded, i can see paper-button showing `2016/12/01` which is correct. 
- Then click the button and dialog opeened it still using today date `2016/08/04`
- The select a date and dialog closed, button still showing date `2016/12/01'`

**Comment by motss** [comment]
@gusdecool The element works fine just that your code is a bit wrong here and there. After deep investigation to your issue, I found that the code you provided are wrong in the syntax and had no idea it works for you (sometimes) and also discovered a small issue while looking into this matter. I already patched it and it worked for your case after that. I will post a demo to show you how to achieve that. Stay tuned~ :smile:

**Comment by motss** [comment]
@gusdecool Thanks for the use case that I managed to discover bug and got it patched. :+1:

**Comment by motss** [comment]
Working demo for your use case: http://jsbin.com/xenanotesa/edit?html,output

**Comment by gusdecool** [comment]
nice it's work now, thanks for the demo 👍
