### ISSUE TITLE
Can't select dates on open dialog

### ISSUE THREAD

**Issue by dmb1987** [motss/app-datepicker#46]
hello, trying to implement a demo "bind-date-to-input-date" , this happens when you open the dialog to select a date , I can not select anything , please help!
thank you very much.
![captura de pantalla de 2016-09-14 13-01-23](https://cloud.githubusercontent.com/assets/15080749/18519814/8dec2c38-7aa5-11e6-82fc-8a7b2f398be8.png)

**Comment by motss** [comment]
@dmb1987 This kind of issue most likely comes from your code and it has nothing to do with the element. Please provide your code for help of debugging.

**Comment by dmb1987** [comment]
<template>
 
    <form is="iron-form" method="post" action="/submit.php" id="formExample">

    
        <bind-date-to-input-date></bind-date-to-input-date>

        <paper-input char-counter error-message="{{error_username}}" name="username" value="{{username}}" label="Username" maxlength="25" required></paper-input>
        <br>
 
        <paper-dropdown-menu label="Cars" name="cars" required>
            <paper-menu class="dropdown-content">
                <paper-item value="volvo">Volvo</paper-item>
                <paper-item value="saab">Saab</paper-item>
                <paper-item value="fiat">Fiat</paper-item>
                <paper-item value="audi">Audi</paper-item>
            </paper-menu>
        </paper-dropdown-menu>
        <br>
 
        <paper-checkbox name="terms" required>I agree</paper-checkbox>
        <br><br>
 
        <paper-button raised class="custom indigo" onclick="document.getElementById('formExample').submit()">
            <iron-icon icon="icons:save"></iron-icon>
            Guardar
        </paper-button>
 
        <div class="output"></div>
        <br>
        <div class="outputServer"></div>
        <br>
    </form>
</template>

**Comment by dmb1987** [comment]
i included 

<link rel="import" href="../bower_components/app-datepicker/app-datepicker.html">
<link rel="import" href="../bower_components/app-datepicker/app-datepicker-dialog.html">
<link rel="import" href="../bower_components/app-datepicker/demo/bind-date-to-input-date.html">

**Comment by motss** [comment]
@dmb1987 I don't think you can put `<bind-date-to-input-date>` right into a `form` element.

**Comment by dmb1987** [comment]
it is the same doing it this way

`<paper-button raised on-tap="openDialog">Datepicker Dialog</paper-button>
            <paper-button disabled>[[dynamicDate]]</paper-button>
            <app-datepicker-dialog id="datepicker" with-backdrop theme="[[theme]]" view="{{view}}" first-day-of-week="[[firstDayOfWeek]]" disable-days="[[disableDays]]" min-date="[[minDate]]" max-date="[[maxDate]]" format="[[format]]" date="{{dynamicDate}}" show-long-date="[[showLongDate]]" locale="[[locale]]"></app-datepicker-dialog>`
