### ISSUE TITLE
To support Polymer v2.0

### ISSUE THREAD

**Issue by motss** [motss/app-datepicker#47]
The release of Polymer v2.0 is imminent and the Polymer teams are working extremely hard to port over existing Polymer 1.x elements to v2.0.

This element has no doubt must be part of the upgrade. We will provide support once Polymer v2.0  is officially released to the public.

Can't wait to see how things work with the latest web platforms in the year of 2016 and yeah Polymer and Web Components FTW!

**Comment by diegocerdan** [comment]
Is the 2.9 version compatible with Polymer 2.0?

**Comment by motss** [comment]
@diegocerdan No. A version to support Polymer 2.0 is still WIP.

**Comment by motss** [comment]
Closing this old issue as the element has already been a hybrid element that supports both Polymer 1.x and 2.x.
