### ISSUE TITLE
Cant get this to work at all

### ISSUE THREAD

**Issue by srk289** [motss/app-datepicker#49]
I am not sure if its just me but I cant get this to work at all. Downloaded through bower, linked all good and when I add &lt;app-datepicker-dialog&gt;&lt;/app-datepicker-dialog&gt; nothing appears. 

when I inspect the DOM for app-datepicker, looks like its loading but nothing appears on the screen. No console errors either. Any one else had this issue?

**Comment by motss** [comment]
@srk289 Please show your reduced test case to ease debugging.

**Comment by srk289** [comment]
[test.zip](https://github.com/motss/app-datepicker/files/486600/test.zip)
added my test files.

**Comment by motss** [comment]
@srk289 Ok. You misunderstood how a dialog works. You need to trigger a dialog to open or it will be hidden forever.

You can open a datepicker dialog from a button for instance. See the example code below to get a better understanding on how to do it in Polymer way.

```html
<app-datepicker-dialog id="openMe"></app-datepicker-dialog>
<button on-click="_openDialog"></button>
```

```js
_openDialog: function (ev) {
  this.$.openMe.open();
},
```

**Comment by motss** [comment]
Closing this issue as it's not the problem from the element.

**Comment by srk289** [comment]
Thanks @motss You are right. Stupid question.  Appreciate your prompt response
