### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by srk289** [motss/app-datepicker#53]
Hi @motss 
Would be great to be able to switch date formats (dd/mm/yyyy)

**Comment by motss** [comment]
@srk289 It can be changed via the property `format`. However, just tested it with the `format` and found a bug. Will get it fixed ASAP.

**Comment by motss** [comment]
@srk289 It's been fixed and added test for many different use cases and combinations. Feel free to reopen if the issue still persists. Once again thank you for reporting the issue.
