### ISSUE TITLE
To fix format

### ISSUE THREAD

**Issue by motss** [motss/app-datepicker#54]
## Description

From #53, a bug was found when changing the default value of `format`, vix. `yyyy/mm/dd` to value like `dd/mm/yyyy` will render the `date` go haywire.
## Step to reproduce

[Live demo](http://jsbin.com/foliwulaje/1/edit?html,output)

**Comment by panuhorsmalahti** [comment]
Side note: it would be nice to just get `Date` values out of the component. At the moment I need to "manually" parse the date string and convert to `Date`. It's also unclear to me if or how the component supports the ISO format for dates, which would make it easy to convert it back to a `Date` value.

**Comment by motss** [comment]
Fixed in `v2.9.0`
