### ISSUE TITLE
Bug: auto-update-date format='yyyy-mm-dd' on-date-changed

### ISSUE THREAD

**Issue by rmgalante** [motss/app-datepicker#55]
I initialize the input-date to today's date. The element shows the correct date. I click the next month button until I reach October of next year. I choose October 2. The event handler, onDateChanged, shows e.detail.value = '2016-10-02'. But I'm in the year, 2017. It should show '2017-10-02'.

This only happens the first time you click a day in the month of the next year. After that, it works and shows the correct year.

**Comment by rmgalante** [comment]
I would like to clarify the problem I see. I've been debugging this and here is what I found. I put some debugging statements in the event handler for the event, date-changed.

I load the page, and the console log shows 2016-10-20.

I change the month from October of 2016 to October of 2017 by clicking the right arrow in the upper right corner until the month of October is shown (same month next year). I click on the day, 31. The console shows one event fired with a value of 2016-10-31. Why is it not reporting 2017-10-31? **This is the date that appears in the left panel => 2017, Mon, Oct 31). That is wrong! It's not Monday.**

I reload the page and click on the year and change it to 2017. Then if I click on the day, 31, I see the correct date, which is 2017-10-31. And the date that appears in the left panel => 2017, Tue, Oct 31). This is right.

So the changed year is detected, when I click the year and change it. But the changed year is not detected when I change the month from October of 2016 to October of 2017 by clicking the right arrow button. So when I click the day of the month, I get the previous year. And the left panel is not showing the correct date.

This only happens the first time I click a day. If I click a different day of the same month, the changed year is detected.

**Comment by motss** [comment]
@rmgalante Issue confirmed. A patch is in progress. Thank you for reporting.
