### ISSUE TITLE
Integration with Angular 2

### ISSUE THREAD

**Issue by JunedS** [motss/app-datepicker#56]
Hi,

First of all this is awesome date picket, keep up the good work!
I am trying to integrate app datepicker with angular 2 using vaadin angular2-polymer directive.
date picker works but I cant get some of the things to work like min-date, max-date, theme and view all works dynamically but cant get input-date, on-date-changed to work. below is the code

<app-datepicker view="vertical" [inputDate]="inpDate" [minDate]="minDate" (date)="selectedDate" (onDateChanged)="onDateChanged()" auto-update-date="true" [theme]="theme" show-long-date="true"></app-datepicker>

Note: min-date is provided as camel case here to make it work but similarly for input-date it doesnt work. Both minDate and InputDate as declared as string with values inpDate = '2016/10/23' and minDate = '2016/10/22'. I can see all dates disabled below 22nd OCT 2016 but 23rd OCT is not selected instead see today's date being selected

Thanks,
Juned S

**Comment by motss** [comment]
@JunedS It would be nice if you could use `jsbin.com` or some sort to create a reduced test case for your issue.

**Comment by motss** [comment]
Closing this old issue.
