### ISSUE TITLE
Some years are selected incorrectly

### ISSUE THREAD

**Issue by n8m** [motss/app-datepicker#57]
Hi. Steps to reproduce:
1. Click on 'year' to select year and choose any year less than 2011
2. You can see that on left side there's 2010 year selected -> weekday and month no more match on the left and right sides on datepicker.

It's reproducing in Chrome and not reproducing in Firefox.
Sorry for Russian locality in attached image

![issue](https://cloud.githubusercontent.com/assets/4228383/19232867/ef769bb0-8eea-11e6-87fc-8f5fa7871b4b.png)

**Comment by motss** [comment]
@n8m Thanks for reporting. Working on a fix.

**Comment by motss** [comment]
`iron-list` is the culprit.

**Comment by userquin** [comment]
see #87 and #88

**Comment by motss** [comment]
Closing this issue as this has been fixed in some other raised issues #87 and #88. Thank you for all the reporting. Really appreciate that! 👍
