### ISSUE TITLE
Add app-datepicker-dialog documentation

### ISSUE THREAD

**Issue by panuhorsmalahti** [motss/app-datepicker#59]
There should be a separate API documentation for this element. This would consist of basically adding documentation (or just links to) for Polymer.PaperDialogBehavior Polymer.NeonAnimationRunnerBehavior.

**Comment by motss** [comment]
@panuhorsmalahti This makes sense for better usage on the dialog as I've seen a lot of users not aware of the dialog.

**Comment by motss** [comment]
Closing this in favor of `v4`. Highly recommend using `v4` even if you are using `polymer`.

Thank you for the support.
