### ISSUE TITLE
Support for displaying week numbers

### ISSUE THREAD

**Issue by panuhorsmalahti** [motss/app-datepicker#64]
I think it would be useful to offer an option for displaying week numbers. I'll start working on a PR. I'll use ISO-8601 week numbering and add an option for displaying them (and by default week numbers won't be displayed).

**Comment by motss** [comment]
@panuhorsmalahti This might be helpful. Feel free to take a peek. https://gist.github.com/motss/627f95897fe4c926c158

**Comment by panuhorsmalahti** [comment]
Thanks, you have nice bag of tricks :)

**Comment by motss** [comment]
For those folks who'd want to try something new out, feel free to take a look at the latest branch I've been working on that addresses this as part of the new rewrite with `lit-html` - https://github.com/motss/app-datepicker/tree/lit-element-v1

**Comment by motss** [comment]
Closing this in favor of official support of week numbers in `v4`.

Highly recommend using `v4` which is still currently in beta.

Thank you for the support.
