### ISSUE TITLE
Days of week are coming in random order

### ISSUE THREAD

**Issue by rip-the-jacker** [motss/app-datepicker#67]
The days of the week in datepicker dialog which should ideally be **'S M T W T F S'** is showing up as **'S F T F S S M'**

![app-datepicker](https://cloud.githubusercontent.com/assets/3167295/19964777/bbb39be0-a1e9-11e6-8d96-a8f967a2023c.png)

But on selecting the date, the proper day of the week is selected.

**Comment by motss** [comment]
@rip-the-jacker This is confirmed. A patch is in progress. New release might come this weekend or so.

**Comment by rip-the-jacker** [comment]
@motss @sp1rs Thank you guys.

**Comment by rip-the-jacker** [comment]
@motss Can I update this using bower?

**Comment by motss** [comment]
@rip-the-jacker @sp1rs [`app-datepicker@2.9.0` is released!`](https://github.com/motss/app-datepicker/releases/tag/v2.9.0)

**Comment by rip-the-jacker** [comment]
Thank you :)
