### ISSUE TITLE
autoUpdateDate in app-datepicker-dialog ?

### ISSUE THREAD

**Issue by sp1rs** [motss/app-datepicker#70]
Do we have autoUpdateDate property in app-datepicker-dialog ?

**Comment by motss** [comment]
By default, app-datepicker needs buttons to confirm on selected date change. Let say app-datepicker was put into a dialog, the selected date should be updated only when the user click on the confirm button within the dialog. If autoUpdateDate was enabled by default, this would always update and fire when the selected date changes. Of course, you can say that let's turn it off when there are buttons or something like that. So this is basically the use case of why autoUpdateDate was proposed and set to false by default. Hope it answered your doubt!~

**Comment by motss** [comment]
Closing issue. Feel free to reopen.
