### ISSUE TITLE
1992: September occurs twice

### ISSUE THREAD

**Issue by millitza** [motss/app-datepicker#72]
The app-datepicker(-dialog) shows the month September twice in the year 1992. I am not sure if the issue is contained to this year only, but it does not appear in the other years I did check.

**Comment by motss** [comment]
@millitza Any steps to reproduce the bug? Unable to reproduce on Chrome 55, Firefox 50, and Edge 14 for Windows. Yet to test on other OSes.

**Comment by motss** [comment]
Closing issue. Feel to reopen.
