### ISSUE TITLE
can't figure out how to create a mixin to change width definitions

### ISSUE THREAD

**Issue by edwardsharp** [motss/app-datepicker#73]
hi there, i'm wanting to change a couple of css width rules, specifically: 

https://github.com/motss/app-datepicker/blob/master/app-datepicker.html#L367
changed to: 
```
width: 100%;
```

https://github.com/motss/app-datepicker/blob/master/app-datepicker.html#L380
changed to: 
```
width:100%;
/*max-width: 164px;*/
```

i can't quite figure out how to create a mixin to override these definitions. is this even possible? i've fiddled around with the `--app-datepicker` mixin but unable to get anything working; either the style doesn't get applied or all the styling goes away.... 

so far i've just made the change to my local copy in bower_components. it seems like my only option is to fork and maintain the small changes myself? is there any way to customize these definitions? 

thank you for any insight!

**Comment by motss** [comment]
@edwardsharp 
Hmm...the only way to do this is to use CSS Variables and the element does not have that ability to set a custom width when it's in other orientations or device's width size.

It can be fixed though with a quick patch release. Do you still need it anyway?

**Comment by edwardsharp** [comment]
hi there, well, no this is not something i really need anymore. i ended up creating my own datepicker implementation to provide the specific style & functionality i desired. 

it does seem like it would be useful to have an inline datepicker that sizes to the parent (e.g. 100% instead of 512px), however i'll leave those aesthetics up to you :)

**Comment by motss** [comment]
Great. Closing issue.
