### ISSUE TITLE
 The inputDate only works if no date was selected before

### ISSUE THREAD

**Issue by CheckHelzio** [motss/app-datepicker#74]
Hi!
First of all thanks for the wonderful work creating this component.

The inputDate works to open the datePicker on a specific date, but after I use the datePicker to select any other date, the inputDate does not work again.

What can I do if I want to open the datePicker always on the same date, even if I already select another one?

**Comment by motss** [comment]
@CheckHelzio May I know what your use case is for this kind of purpose? I'd like to know a little bit more on what approach to best suit your use case. And I understand you want it to be able to reset to the given `inputDate` everytime the datepicker opens. Am I correct?

**Comment by CheckHelzio** [comment]
I am developing an application that is a calendar of the events that will be in my university.

I use the datePicker to navigate faster to a specific date. Also as a shortcut to return to today.

I use it also to generate reports of the events, selecting the initial and final date of the report.

**Comment by sp1rs** [comment]
@motss Yes, whenever the datepicker opens, I would like to reset the inputDate.
And also I have something like this.
```
<app-datepicker id="picker" date="{{testDate}}"></app-datepicker>

this.$.picker.inputDate = x;
# Then testDate was set as x?
```

testDate was set as date which I gave in inputDate? Is this the right flow?

**Comment by motss** [comment]
@sp1rs reset `inputDate` or resete `selectedDate`?

**Comment by sp1rs** [comment]
@motss both inputDate and selectedDate.

**Comment by sp1rs** [comment]
@motss  and why setting `inputDate`, changes `data` also ?

**Comment by motss** [comment]
@sp1rs `inputDate` will directly affect the selected date internally but that does not actually update the `date` which will output the selected date. Why? It's because `app-datepicker` usually use within  a dialog and only clicking the OK button will trigger updating the value `date` whereas CANCEL button means you don't want to output the selected date. But for `app-datepicker` has another method called `enforceDateChange` which will update the `app-datepicker` (not `app-datepicker-dialog`).

**Comment by motss** [comment]
@sp1rs The use case to me is quite rare. The only way to do is to introduce a flag for this kind of use case.

**Comment by motss** [comment]
@sp1rs @CheckHelzio cd8d97c should fix this with newly added flag `alwaysResetSelectedDateOnDialogClose`.

**Comment by motss** [comment]
The demo always updated with this rare use case. PTAL. 👍 

[Updated demo with alwaysReset flag](https://motss.github.io/app-datepicker/components/app-datepicker/)

**Comment by sp1rs** [comment]
Thanks, @motss

**Comment by sp1rs** [comment]
@motss When is the fix going live?

**Comment by motss** [comment]
@sp1rs Since the Polymer 2.0 went stable, I'm still working on maybe this can be a hybrid element for the latest stable version alongside this patch. Of course, as always, help are definitely welcomed. Stay tuned~

**Comment by motss** [comment]
@sp1rs Please check out the latest release which has been upgraded into a hybrid Polymer Element! 🌮 🎉

**Comment by sp1rs** [comment]
@motss awesome, thanks a lot.
