### ISSUE TITLE
Support for swipe gesture

### ISSUE THREAD

**Issue by wingliu0** [motss/app-datepicker#77]
I think it is cool to support swiping, just like the one in android

**Comment by motss** [comment]
@wingliu0 Thank you for your support. This feature is not likely to be included in the current version. However this feature has been backlogged alongside Polymer 2.0. It will be released as soon as possible once Polymer goes stable in version 2.0.

**Comment by wingliu0** [comment]
@motss cool. Im looking forward to the 2.0 version

**Comment by motss** [comment]
Once again thank you.
