### ISSUE TITLE
Properties "date" seem to not be two ways data binding

### ISSUE THREAD

**Issue by Adesfire** [motss/app-datepicker#78]
As i specify the "min-date" to be 10 days later than today (so the days before are disabled), i wanted forcing the "date" property, to be 10 days after today. This way, my customers will don't see a "all red calendar" when we are after the 20 of the month.

The problem is, when i change the "date" property of the app-datepicker, the selected day is not modified (still set on today). I have set the auto-update-date but i think it's not in link with that.

There is a way to achieve that, or it's not a feature available currently ?

Regards.

**Comment by motss** [comment]
@Adesfire There are `date` and `inputDate` properties which are seemed to be confusing at first but hopefully the brief explanation below will help you out:

* `inputDate` - receive date input.

* `date` - output date after selection.

Hence, for you case, I think you should:

```html
<app-datepicker min-date="2017/03/23" input-date="2017/03/25"></app-datepicker>
```
