### ISSUE TITLE
app-datepicker.js not found

### ISSUE THREAD

**Issue by nicolasr75** [motss/app-datepicker#79]
I tried the 2.0 preview version in a test project and got _404 app-datepicker.js not found_ because in app-datepicker.html there is this reference

    <script src="/app-datepicker.js"></script>

Is there a reason why you don't include the js code in the html file? Am I supposed to copy that file to my root folder?

**Comment by motss** [comment]
@nicolasr75 The `2.0-preview` is undergoing major overhaul and it's not ready to be used. Sorry for the inconvenience this may cause you. I'll update the README once it's ready.
