### ISSUE TITLE
Date format breaks in the new Chrome v58

### ISSUE THREAD

**Issue by rip-the-jacker** [motss/app-datepicker#80]
Before updating chrome, selecting date used to show proper date format. But now the date is shown in a weird way with month denoted by number instead. PFA before and after Chroime update.

**Before**
![correct value](https://cloud.githubusercontent.com/assets/3167295/25485043/faac8a2c-2b79-11e7-8155-65131286f00e.png)

**After**
<img width="318" alt="screen shot 2017-04-27 at 6 42 02 pm" src="https://cloud.githubusercontent.com/assets/3167295/25485069/151f5bc8-2b7a-11e7-8841-0242ab69eb69.png">

**Comment by motss** [comment]
@rip-the-jacker 

Need for info:

1. Affected OS version
2. Browser language
3. Polymer version
4. Affected `app-datepicker` version
5. A reduced test case to reproduce the issue.

**Comment by rip-the-jacker** [comment]
- Affected OS version
  **Mac OSX 10.12.4**
- Browser language
  **English (US)**
- Polymer version
  **1.9.1**
- Affected app-datepicker version
  **2.9.0**
- A reduced test case to reproduce the issue.
  **Pick any date in datepicker, instead of verbose name of month. it just shows the number as shown in the image.**

**Comment by motss** [comment]
Will look into it in depth to see if it can be reproduced.

**Comment by sp1rs** [comment]
@rip-the-jacker 
Just added locale='en' and it worked fine for me.

**Comment by rip-the-jacker** [comment]
@sp1rs Thanks that works.

**Comment by motss** [comment]
@rip-the-jacker 

Tested the issue throughly on all browsers on latest macOS and was unable to reproduce the issue.

Yell at me again for persistent issue.

Thank you for reporting. 😄

**Comment by rip-the-jacker** [comment]
@motss I had set format="". Maybe that's what caused it.

**Comment by motss** [comment]
Hmm...that's could be what worth looking into.

**Comment by sp1rs** [comment]
The issue is ..
Chrome: 57 : window.Intl.DateTimeFormat().resolvedOptions().locale ==> 'en-gb'
Chrome 58 :  window.Intl.DateTimeFormat().resolvedOptions().locale ==> 'und'

And i just updated the chrome from 57 to 58. Somehow the locale changed.

@motss, Can we have check that if locale is undefined 'und' than use 'en' as default.

**Comment by motss** [comment]
@sp1rs Strange enough. Mine is still `en-US`.

**Comment by sp1rs** [comment]
@motss Did you updated the chrome to 58?

**Comment by motss** [comment]
@sp1rs Tested on Chrome 58, 59, 60 and all returned `en-US`.

**Comment by sp1rs** [comment]
@motss Still, if `window.Intl.DateTimeFormat().resolvedOptions().locale` returns `und` then code should handle this case.

**Comment by motss** [comment]
@sp1rs Indeed. This is definitely needed to be fixed.

**Comment by sp1rs** [comment]
@motss I was about to create a pull request, but you fixed it.
