### ISSUE TITLE
input-date property does not respect the format given

### ISSUE THREAD

**Issue by FLamparski** [motss/app-datepicker#85]
### Description
Given a `<app-date-picker format="yyyy-mm-dd" input-date=[[someVar]]></app-date-picker> == $0`:

```javascript
$0.inputDate = '2017-05-23'
// nothing
$0.inputDate = '2017/05/23'
// date is changed
```

### Expected outcome

The date selected in the datepicker should change as a new input-date is set which follows the format given by the format attribute

### Actual outcome

The selected date only changes if the format it's given in is YYYY/MM/DD

### Live Demo

N/A

### Steps to reproduce

1. Put app-datepicker on a page
2. Specify format
3. Select it in devtools and start throwing values into `$0.inputDate`

(Alternatively, go to the component's demo page, set the format from devtools, then play with the input field - you'll notice that it says the input date is invalid even if it matches the format you give to the date picker)

### Browsers Affected

- [x] Chrome/ Opera
- [x] Firefox
Not tested:
- [ ] Safari 10+
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge 12+
- [ ] IE 11

**Comment by motss** [comment]
@FLamparski Though a bit late, this has been patched.
