### ISSUE TITLE
datepicker went haywire before year 1983 is selected

### ISSUE THREAD

**Issue by motss** [motss/app-datepicker#88]
### Description

Dates went haywire when any year before 1983 is selected. This could be related to the `Date` object implemented on the browsers and further investigation is needed to dive the issue down to figure the cause out. Otherwise, nothing can be done since it's a web platform issue.

### Expected outcome

Dates should be computed as how dates are computed after year 1983.

### Actual outcome

Dates went haywire when any year before 1983 is selected.

### Steps to reproduce

Go to demo page and select any date before year 1983 in datepicker.

### Browsers Affected

- [x] Chrome/ Opera
- [x] Firefox
- [ ] Safari 10+
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge 12+
- [ ] IE 11

**Comment by motss** [comment]
@userquin Related to #87.

**Comment by userquin** [comment]
it seems you need to work with UTC: instead using new Date(y,m,d) you need to change it to new Date(Date.UTC(y,m,d)): beware Date.UTC month is 1 based instead of 0 based

**Comment by userquin** [comment]
new window.Intl.DateTimeFormat('es-ES', { day: 'numeric' }).format(new Date(1995,8,25));
"24"
new window.Intl.DateTimeFormat('es-ES', { day: 'numeric' }).format(new Date(Date.UTC(1995,9,25)));
"25"

**Comment by userquin** [comment]
It seems Intl accumulates offsets, I'm from Spain GMT+1 with DST (GMT+2 in summer time)

**Comment by userquin** [comment]
I have it working, you only have to change a few new Date to Date.UTC. I suggest you to include in the doc to use the string value to date datepicker value.

**_readOnlyDate**: will be the string used in: 
```javascript
   properties: {
      format: {
        type: String,
        value: function() {
          return 'yyyy/mm/dd';
         }
       },
       _readOnlyDate: String
   }
```
```html
  <app-datepicker date="[[_readOnlyDate]]" format="[[format]]"...></app-datepicker>
```
If the returned value is to be shown, split the _readOnlyDate string with the separator supplied (in this case **/**) to build a Date for the client timezone and then use it to build a Date.UTC to print it:
```javascript
var dateFromPicker = new Date(this._readOnlyDate.replace(/\//g, '-').split('-'));
var dateFromPickerString = new Intl.DateTimeFormat({}).format(Date.UTC(
  dateFromPicker.getFullYear(), 
  dateFromPicker.getMonth(), 
  dateFromPicker.getDate()
);
```

I attach patch for latest version 2.10.1:

[app-datepicker-2.10.1.patch.zip](https://github.com/motss/app-datepicker/files/1068989/app-datepicker-2.10.1.patch.zip)

**Comment by motss** [comment]
@userquin 

This is confirmed. By changing `new Date` to `Date.UTC` will likely solve the whole mystery. Would you like to submit a PR to fix this instead?

**Comment by userquin** [comment]
I have tested on windows 10 and android (chrome) and we also need to add timeZone: 'UTC' to DateTimeFormat options: data on screen must be consistent with their data. 
I'll check in all environments and then I'll try to make a PR as soon as posible...
