### ISSUE TITLE
PR #89 must be reviewed to handle min and max dates

### ISSUE THREAD

**Issue by userquin** [motss/app-datepicker#90]
It seems we also need to change _isDisableDays function to do logic with UTC instead with local TZ.

**Comment by userquin** [comment]
I'm working on it, so when finished I'll make a new PR if necessary...

**Comment by motss** [comment]
@userquin Cool.

**Comment by userquin** [comment]
@motss , I have a problem. I have merge my PR #89 to my master and then create a new branch for PR #90 from my master  but when I request a new one PR for your repo all changes from PR #88 when I  compare across forks.

**Comment by userquin** [comment]
You have moved PR #89 to 2.11.0, my repo comes from 2.10.1. I think you dont have problems merging to 2.11.0.
